---
title:
  name: "Get Into Teaching"

projects:
 - api:
   ref:       "DFE-Digital/get-into-teaching-api"
   name:      "Get Into Teaching API"
   environments:
      - name: "Development"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
      - name: "Quality Assurance"
        deployment_workflow: "Release to Test"
        release_prefix:  "QA"
      - name: "User Research Testing"
        deployment_workflow: "Release to UR"
        release_prefix:  "UR"
      - name: "Production"
        deployment_workflow: "Release to Production"
        release_prefix:  "UR"
 - app:
   ref:        "DFE-Digital/get-into-teaching-content"
   name:      "Get Into Teaching Content"
   environments:
      - name: "Development"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
      - name: "Quality Assurance"
        deployment_workflow: "Release to test"
        release_prefix:  "QA"
      - name: "User Research Testing"
        deployment_workflow: "Release to User Research (UR)"
        release_prefix:  "UR"
      - name: "Production"
        deployment_workflow: "Release to Production"
        release_prefix:  "UR"

 - tta:
   ref:       "DFE-Digital/get-teacher-training-adviser-service"
   name:      "Teacher Training Adviser"
   environments:
      - name: "Development"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
      - name: "Quality Assurance"
        deployment_workflow: "Release to test"
        release_prefix:  "QA"
      - name: "User Research Testing"
        deployment_workflow: "Release to User Research (UR)"
        release_prefix:  "UR"
      - name: "Production"
        deployment_workflow: "Release to Production"
        release_prefix:  "UR"
 - app:
   ref:        "DFE-Digital/get-into-teaching-app"
   name:      "Get Into Teaching APP"
   environments:
      - name: "Development"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
 - test:
   ref:        "DFE-Digital/get-into-teaching-frontend-tests"
   name:      "Get Into Teaching Testing"
   environments:
      - name: "Cypress Frontend Tests"
        deployment_workflow: "Cypress Testing against Test Environment"
        deployment_branch:   "master"
