---
title:
  name: "Get Into Teaching"

projects:
 - api:
   ref:       "DFE-Digital/get-into-teaching-api"
   name:      "Get Into Teaching API"
   environments:
      - name: "Development Space"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
        releases:
             allowed: false
      - name: "Test Space"
        deployment_workflow: "Release to Test"
        graph: 
           max_time: 2000
      - name: "Production Space"
        deployment_workflow: "Release to Production"

 - con:
   ref:        "DFE-Digital/get-into-teaching-content"
   name:      "Get Into Teaching Content"
   environments:
      - name: "Development"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
        releases:
             allowed: false
      - name: "Quality Assurance"
        deployment_workflow: "Release to test"
      - name: "User Research Testing"
        deployment_workflow: "Release to User Research (UR)"
      - name: "Production"
        deployment_workflow: "Release to Production"

 - tta:
   ref:       "DFE-Digital/get-teacher-training-adviser-service"
   name:      "Teacher Training Adviser"
   environments:
      - name: "Development"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
        releases:
             allowed: false
      - name: "Quality Assurance"
        deployment_workflow: "Release to test"
      - name: "User Research Testing"
        deployment_workflow: "Release to User Research (UR)"
      - name: "Production"
        deployment_workflow: "Release to Production"

 - app:
   ref:        "DFE-Digital/get-into-teaching-app"
   name:      "Get Into Teaching APP"
   environments:
      - name: "Development"
        deployment_workflow: "Build and Deploy"
        deployment_branch:   "master"
        releases:
             allowed: false

 - test:
   ref:        "DFE-Digital/get-into-teaching-frontend-tests"
   name:      "Get Into Teaching Testing"
   environments:
      - name: "Cypress Frontend Tests"
        deployment_workflow: "Cypress Testing against Test Environment"
        deployment_branch:   "master"
        releases:
             allowed: false
